version: "2.1"

services:

  workshop-kotlin-for-java-devs:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ["workshop-kotlin-for-java-devs-data:/home/appuser"]
    networks: [backing-services]
    #ports: ["8080:8080"]
    #restart: unless-stopped
    #mem_limit: 209715200 # container limit: 200Mb (200 * 1024 * 1024)

volumes:
  workshop-kotlin-for-java-devs-data: {}

networks:
  backing-services:
    driver: bridge
